#' Run the desire specification from a SpANOVA object
#'
#' This function runs the desire specification from a SpANOVA object, using the data prepare from the original specification
#'
#' @param SpANOVA_obj Object generated after running the inla.SpANOVA.2x2 function
#' @param n_mod Number of the model that you want to run, using the value reflected in the SpANOVA summary table
#' @param gr Graph for the underlying spatial structure
#' @param scale.mod Scale copies of random spatial effects or not, default is TRUE
#' @param sp.prior Select prior for the random spatial effect, options are sdunif and pc.prec
#' @param pc.prec.val Define values por the pc prior in case it was chosen. Default values are c(1, 0.01)
#' @param sp.copy.fixed Fix copied values for the random spatial effects, default is TRUE
#' @param verbose.INLA Change verbose value for INLA in case you want to follow the approximation
#' @return Object generated by INLA, including groups and sp_effects data from the SpANOVA specification
#' @export

inla.rerun.SpANOVA <- function(SpANOVA_obj, n_mod, gr, scale.mod=TRUE, sp.prior="sdunif", pc.prec.val = c(1, 0.01), sp.copy.fixed=TRUE, verbose.INLA=FALSE) {

  ## Print warnings (warnings are printed as they occur)
  options(warn=1)

  ## Define uniform priors for the standard deviation
  if(sp.prior=="sdunif"){
    prior.prec <- list(prior = "expression: log_dens = 0 - log(2) - theta / 2; return(log_dens);", initial = 0)
  }else if(sp.prior=="pc.prec"){prior.prec <- list(prior = "pc.prec", param = pc.prec.val)}

  ## Define sp model
  sp.model <- "besag"

  ## Define number of levels and number of areas
  n.levels <- c(2, 2)
  n.areas <- gr$n

  ## Get maximum number of groups/diseases
  n.groups <- base::prod(n.levels)

  ## Extract model
  mod_temp <- SpANOVA_obj[[n_mod]]

  ## Detect if the SpANOVA object contains appropriate information
  if(!("alpha" %in% names(mod_temp))){stop("SpANOVA object does not contain the necessary information, please rerun original SpANOVA with save.mod.data=TRUE")}

  ## Empty list
  data.INLA <- data.frame("obs" = mod_temp$obs, "exp" = mod_temp$exp, "alpha" = mod_temp$alpha)
  formula <- mod_temp$formula

  ## Create IDs for each area and group
  data.INLA$AREAID <- rep(1:n.areas, n.groups)

  ## Create IDs for shared spatial effects - phi
  data.INLA$ID_g1 <- data.INLA$AREAID
  data.INLA$ID_g1[-c(1:n.areas)] <- NA
  data.INLA$ID_g2 <- data.INLA$AREAID
  data.INLA$ID_g2[-(n.areas + 1:n.areas)] <- NA
  data.INLA$ID_g3 <- data.INLA$AREAID
  data.INLA$ID_g3[-(2 * n.areas + 1:n.areas)] <- NA
  data.INLA$ID_g4 <- data.INLA$AREAID
  data.INLA$ID_g4[-(3 * n.areas + 1:n.areas)] <- NA

  ## Create IDs for IID Effect - omega_j
  data.INLA$omega_j <- 1:(n.areas*4)

  ## Create IDs for shared spatial effects
  if(n_mod==2){
    # Individual spatial effects - phi_g
    data.INLA$phi_1 <- data.INLA$ID_g1
    data.INLA$phi_2 <- data.INLA$ID_g2
    data.INLA$phi_3 <- data.INLA$ID_g3
    data.INLA$phi_4 <- data.INLA$ID_g4
  }else if(n_mod %in% c(3, 4, 5, 6)){
    # Define IDs for overall shared spatial effect - phi_11
    data.INLA$phi_11 <- data.INLA$ID_g1
    data.INLA$phi_11_g2 <- data.INLA$ID_g2
    data.INLA$phi_11_g3 <- data.INLA$ID_g3
    data.INLA$phi_11_g4 <- data.INLA$ID_g4
  }else if(n_mod %in% c(7, 8)){
    # Overall shared spatial effect - phi_11
    data.INLA$phi_11 <- data.INLA$ID_g1
    data.INLA$phi_11_g2 <- data.INLA$ID_g2
    data.INLA$phi_11_g3 <- data.INLA$ID_g3
    data.INLA$phi_11_g4 <- data.INLA$ID_g4

    # Define IDs for 2-group shared effect - phi_21
    data.INLA$phi_21  <- data.INLA$ID_g3
    data.INLA$phi_21_g4 <- data.INLA$ID_g4
  }else if(n_mod %in% c(9, 10)){
    # Overall shared spatial effect - phi_11
    data.INLA$phi_11 <- data.INLA$ID_g1
    data.INLA$phi_11_g2 <- data.INLA$ID_g2
    data.INLA$phi_11_g3 <- data.INLA$ID_g3
    data.INLA$phi_11_g4 <- data.INLA$ID_g4

    # Define IDs for 2-group shared effect - phi_21
    data.INLA$phi_12  <- data.INLA$ID_g2
    data.INLA$phi_12_g4 <- data.INLA$ID_g4
  }else if(n_mod %in% c(11, 12, 13, 14)){
    # Define IDs for overall shared spatial effect - phi_11
    data.INLA$phi_11 <- data.INLA$ID_g1
    data.INLA$phi_11_g2 <- data.INLA$ID_g2
    data.INLA$phi_11_g3 <- data.INLA$ID_g3
    data.INLA$phi_11_g4 <- data.INLA$ID_g4

    # Define IDs for 2 groups shared effect - phi_12
    data.INLA$phi_21  <- data.INLA$ID_g3
    data.INLA$phi_21_g4 <- data.INLA$ID_g4

    # Define IDs for 2 groups shared effect - phi_21
    data.INLA$phi_12 <- data.INLA$ID_g2
    data.INLA$phi_12_g4 <- data.INLA$ID_g4
  }else if(n_mod %in% c(15:22)){
    # Overall shared spatial effect - phi_11
    data.INLA$phi_11 <- data.INLA$ID_g1
    data.INLA$phi_11_g2 <- data.INLA$ID_g2
    data.INLA$phi_11_g3 <- data.INLA$ID_g3
    data.INLA$phi_11_g4 <- data.INLA$ID_g4

    # # Define IDs for 2 groups shared effect - phi_12
    data.INLA$phi_21  <- data.INLA$ID_g3
    data.INLA$phi_21_g4 <- data.INLA$ID_g4

    # # Define IDs for individual effect 1 - phi_21
    data.INLA$phi_12 <- data.INLA$ID_g2

    # # Define IDs for individual effect 2 - phi_22
    data.INLA$phi_22 <- data.INLA$ID_g4
  }

  ####################################################### RUN THE MODEL #######################################################

  try(ResMod <- INLA::inla(formula = formula, data = data.INLA, family = rep("poisson", 4), E = data.INLA$exp,
                           control.predictor = list(compute = TRUE), control.compute = list(dic = TRUE, waic = TRUE, cpo = TRUE),
                           control.inla = list(tolerance.step = 1e-8)), verbose=verbose.INLA)

  ####################################################### RESULTS #######################################################
  if(exists("ResMod")){

    ResMod$groups <- mod_temp$groups
    ResMod$sp_effects <- mod_temp$sp_effects

  }else{
    stop("INLA Failed, re-run with verbose.INLA=TRUE to check where the issue was.")
  }

  # Return INLA model
  return(ResMod)
}
